version: '3.8'

services:
  liquid-api:
    build:
      context: ../LiquidAPI
      dockerfile: ../Docker/api.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DatabaseSettings:ConnectionString=mongodb://liquid-mongo:27017
      - ASPNETCORE_URLS=http://+:5000

  liquid-mongo:
    image: mongo:latest
    container_name: liquid-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  liquid-vue:
    build:
      context: ../LiquidVue
      dockerfile: ../Docker/vue.Dockerfile
    ports:
      - "8080:8080"

  liquid-postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  mynetwork:

volumes:
  mongodb_data:
  pgdata:
